[package]
name = "mmaction-install"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "setup"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
console = "0.15"
glob = "0.3"
indicatif = "0.17"
